apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-lb
  namespace: default
spec:
  entryPoints:
    - websecure  # Changed from 'web' to 'websecure'
  routes:
    - match: Host(`whoami.com`)
      kind: Rule
      services:
        - name: whoami-v1-svc
          port: 80
        - name: whoami-v2-svc
          port: 80
#      middlewares: # Middleware Definition
#        - name: ip-allowlist
  tls:
    secretName: whoami-tls  # Added TLS configuration