apiVersion: v1
kind: Service
metadata:
  name: whoami-v1-svc
  namespace: default
spec:
  selector:
    app: v1
  ports:
    - port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-v2-svc
  namespace: default
spec:
  selector:
    app: v2
  ports:
    - port: 80