apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-mirror
  namespace: default
spec:
  entryPoints:
    - websecure  # Changed from 'web' to 'websecure'
  routes:
    - match: Host(`whoami.com`)
      kind: Rule
      services:
        - name: mirror
          kind: TraefikService

  tls:
    secretName: whoami-tls  # Added TLS configuration