apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-wrr
  namespace: default
spec:
  entryPoints:
    - websecure  # Changed from 'web' to 'websecure'
  routes:
    - match: Host(`whoami.com`)
      kind: Rule
      services:
        - name: wrr
          kind: TraefikService

#      middlewares: # Middleware Definition
#        - name: ip-allowlist
  tls:
    secretName: whoami-tls  # Added TLS configuration