apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: whoami-tcp
  namespace: default
spec:
  parentRefs:
    - name: traefik-gateway
      sectionName: web2
      kind: Gateway

  rules:
    - backendRefs:
        - name: whoamitcp
          namespace: default
          port: 3000