apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
  namespace: default
spec:
  entryPoints:
    - websecure  # Changed from 'web' to 'websecure'
  routes:
    - match: Host(`whoami2.com`)
      kind: Rule
      services:
        - name: whoami
          port: 80
      middlewares: # Middleware Definition
        - name: ip-allowlist
  tls:
    secretName: whoami-tls  # Added TLS configuration