apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: whoami-gateway
  namespace: default
spec:
  gatewayClassName: traefik
  entryPoints:
    web3:
      address: :40000
      observability:
        accessLogs: false
        metrics: false
        tracing: false

  listeners:
    - name: web3
      protocol: HTTP
      port: 40000
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: whoami-http
  namespace: default
spec:
  parentRefs:
    - name: whoami-gateway
      sectionName: http9999
      kind: Gateway
  hostnames:
    - whoami3.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: whoami
          namespace: default
          port: 80



